# Dicas

def devolve_dica(palavra):
    dicas_palavras = {'bola': 'objeto',
                        'casa': 'bjeto',
                        'massa': 'objeto ou alimento',
                        'mesa': 'objeto',
                        'computador': 'objeto',
                        'carro': 'objeto',
                        'casa': 'lugar',
                        'rua': 'lugar',
                        'avenida': 'lugar',
                        'praia': 'lugar',
                        'areia': 'objeto',
                        'tijolo': 'objeto',
                        'celular': 'objeto',
                        'garrafa': 'objeto',
                        'arroz': 'alimento',
                        'carne': 'alimento',
                        'galinha': 'animal',
                        'cachorro': 'animal',
                        'gato': 'animal',
                        'cavalo': 'animal',
                        'macaco': 'animal',
                        'homem': 'substantivo',
                        'mulher': 'substantivo',
                        'cama': 'objeto',
                        'estacionamento': 'lugar',
                        'escola': 'lugar',
                        'professor': 'profissão',
                        'bombeiro': 'profissão',
                        'policial': 'profissão',
                        'cadeira': 'objeto',
                        'tesoura': 'objeto',
                        'faca': 'objeto',
                        'foice': 'objeto',
                        'alicate': 'objeto',
                        'chave': 'objeto',
                        'caixa': 'objeto',
                        'bermuda': 'roupa',
                        'camiseta': 'roupa',
                        'cueca': 'roupa',
                        'meia': 'roupa',
                        'valterwilliansdasila': 'nois roba vai roubar de faca irmão ?'
                        }
    return dicas_palavras[palavra]

